export const INIT_CART = 'INIT_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART_PRODUCTS = 'GET_CART_PRODUCTS';
export const GET_CART_PRODUCT = 'GET_CART_PRODUCT';

const INIT_CART_REQUEST = `${INIT_CART}_REQUEST`;
const INIT_CART_SUCCESS = `${INIT_CART}_SUCCESS`;
const UPDATE_CART_REQUEST = `${UPDATE_CART}_REQUEST`;
const UPDATE_CART_SUCCESS = `${UPDATE_CART}_SUCCESS`;
const ADD_TO_CART_REQUEST = `${ADD_TO_CART}_REQUEST`;
const ADD_TO_CART_SUCCESS = `${ADD_TO_CART}_SUCCESS`;
const REMOVE_FROM_CART_REQUEST = `${REMOVE_FROM_CART}_REQUEST`;
const REMOVE_FROM_CART_SUCCESS = `${REMOVE_FROM_CART}_SUCCESS`;
const GET_CART_PRODUCTS_REQUEST = `${GET_CART_PRODUCTS}_REQUEST`;
const GET_CART_PRODUCTS_SUCCESS = `${GET_CART_PRODUCTS}_SUCCESS`;
const GET_CART_PRODUCT_REQUEST = `${GET_CART_PRODUCT}_REQUEST`;
const GET_CART_PRODUCT_SUCCESS = `${GET_CART_PRODUCT}_SUCCESS`;

export default {
    INIT_CART_REQUEST,
    INIT_CART_SUCCESS,
    ADD_TO_CART_REQUEST,
    ADD_TO_CART_SUCCESS,
    REMOVE_FROM_CART_REQUEST,
    REMOVE_FROM_CART_SUCCESS,
    GET_CART_PRODUCTS_REQUEST,
    GET_CART_PRODUCTS_SUCCESS,
    GET_CART_PRODUCT_REQUEST,
    GET_CART_PRODUCT_SUCCESS,
    UPDATE_CART_REQUEST,
    UPDATE_CART_SUCCESS
};
