const INIT_CART = 'INIT_CART';
const UPDATE_CART_REQUEST = 'UPDATE_CART_REQUEST';
const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST';
const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
const REQUEST_CART_PRODUCTS = 'REQUEST_CART_PRODUCTS';
const RECEIVE_CART_PRODUCTS = 'RECEIVE_CART_PRODUCTS';
const REQUEST_CART_PRODUCT = 'REQUEST_CART_PRODUCT';
const RECEIVE_CART_PRODUCT = 'RECEIVE_CART_PRODUCT';

export default {
    INIT_CART,
    ADD_TO_CART_REQUEST,
    ADD_TO_CART_SUCCESS,
    REMOVE_FROM_CART_REQUEST,
    REMOVE_FROM_CART_SUCCESS,
    REQUEST_CART_PRODUCTS,
    RECEIVE_CART_PRODUCTS,
    REQUEST_CART_PRODUCT,
    RECEIVE_CART_PRODUCT,
    UPDATE_CART_REQUEST,
    UPDATE_CART_SUCCESS
};
