export const INIT_CART = 'INIT_CART';
export const SYNC_CART = 'SYNC_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART_PRODUCTS = 'GET_CART_PRODUCTS';
export const GET_CART_PRODUCT = 'GET_CART_PRODUCT';

const INIT_CART_REQUEST = `${INIT_CART}_REQUEST`;
const INIT_CART_SUCCESS = `${INIT_CART}_SUCCESS`;
const INIT_CART_FAILURE = `${INIT_CART}_FAILURE`;
const SYNC_CART_REQUEST = `${SYNC_CART}_REQUEST`;
const SYNC_CART_SUCCESS = `${SYNC_CART}_SUCCESS`;
const SYNC_CART_FAILURE = `${SYNC_CART}_FAILURE`;
const UPDATE_CART_REQUEST = `${UPDATE_CART}_REQUEST`;
const UPDATE_CART_SUCCESS = `${UPDATE_CART}_SUCCESS`;
const UPDATE_CART_FAILURE = `${UPDATE_CART}_FAILURE`;
const ADD_TO_CART_REQUEST = `${ADD_TO_CART}_REQUEST`;
const ADD_TO_CART_SUCCESS = `${ADD_TO_CART}_SUCCESS`;
const ADD_TO_CART_FAILURE = `${ADD_TO_CART}_FAILURE`;
const REMOVE_FROM_CART_REQUEST = `${REMOVE_FROM_CART}_REQUEST`;
const REMOVE_FROM_CART_SUCCESS = `${REMOVE_FROM_CART}_SUCCESS`;
const REMOVE_FROM_CART_FAILURE = `${REMOVE_FROM_CART}_FAILURE`;

export default {
    INIT_CART_REQUEST,
    INIT_CART_SUCCESS,
    INIT_CART_FAILURE,
    SYNC_CART_REQUEST,
    SYNC_CART_SUCCESS,
    SYNC_CART_FAILURE,
    ADD_TO_CART_REQUEST,
    ADD_TO_CART_SUCCESS,
    ADD_TO_CART_FAILURE,
    REMOVE_FROM_CART_REQUEST,
    REMOVE_FROM_CART_SUCCESS,
    REMOVE_FROM_CART_FAILURE,
    UPDATE_CART_REQUEST,
    UPDATE_CART_SUCCESS,
    UPDATE_CART_FAILURE
};
