const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST';
const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
const REQUEST_CART_PRODUCTS = 'REQUEST_CART_PRODUCTS';
const RECEIVE_CART_PRODUCTS = 'RECEIVE_CART_PRODUCTS';

export default {
    ADD_TO_CART_REQUEST,
    ADD_TO_CART_SUCCESS,
    REMOVE_FROM_CART_REQUEST,
    REMOVE_FROM_CART_SUCCESS,
    REQUEST_CART_PRODUCTS,
    RECEIVE_CART_PRODUCTS
};
