const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
const SET_PRODUCTS_FILTER = 'SET_PRODUCTS_FILTER';

export default {
    REQUEST_PRODUCTS,
    RECEIVE_PRODUCTS,
    SET_PRODUCTS_FILTER
};
