export const GET_PRODUCTS = 'GET_PRODUCTS';

const GET_PRODUCTS_REQUEST = `${GET_PRODUCTS}_REQUEST`;
const GET_PRODUCTS_SUCCESS = `${GET_PRODUCTS}_SUCCESS`;

export default {
    GET_PRODUCTS_REQUEST,
    GET_PRODUCTS_SUCCESS
};
