export const GET_PRODUCTS = 'GET_PRODUCTS';

const GET_PRODUCTS_REQUEST = `${GET_PRODUCTS}_REQUEST`;
const GET_PRODUCTS_SUCCESS = `${GET_PRODUCTS}_SUCCESS`;
const GET_PRODUCTS_FAILURE = `${GET_PRODUCTS}_FAILURE`;

export default {
    GET_PRODUCTS_REQUEST,
    GET_PRODUCTS_SUCCESS,
    GET_PRODUCTS_FAILURE
};
