const LOGOUT = 'LOGOUT';
export const GET_MY_PROFILE = 'GET_MY_PROFILE';

const GET_MY_PROFILE_REQUEST = `${GET_MY_PROFILE}_REQUEST`;
const GET_MY_PROFILE_SUCCESS = `${GET_MY_PROFILE}_SUCCESS`;
const LOGOUT_REQUEST = `${LOGOUT}_REQUEST`;
const LOGOUT_SUCCESS = `${LOGOUT}_SUCCESS`;

export default {
    GET_MY_PROFILE_REQUEST,
    GET_MY_PROFILE_SUCCESS,
    LOGOUT_REQUEST,
    LOGOUT_SUCCESS
};
