export const ADD_CATEGORY = 'ADD_CATEGORY';

export const ADD_CATEGORY_REQUEST = `${ADD_CATEGORY}_REQUEST`;
export const ADD_CATEGORY_SUCCESS = `${ADD_CATEGORY}_SUCCESS`;
export const ADD_CATEGORY_FAILURE = `${ADD_CATEGORY}_FAILURE`;

export default {
    ADD_CATEGORY_REQUEST,
    ADD_CATEGORY_SUCCESS,
    ADD_CATEGORY_FAILURE
};
