export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';

export const ADD_CATEGORY_REQUEST = `${ADD_CATEGORY}_REQUEST`;
export const ADD_CATEGORY_SUCCESS = `${ADD_CATEGORY}_SUCCESS`;
export const ADD_CATEGORY_FAILURE = `${ADD_CATEGORY}_FAILURE`;
export const REMOVE_CATEGORY_REQUEST = `${REMOVE_CATEGORY}_REQUEST`;
export const REMOVE_CATEGORY_SUCCESS = `${REMOVE_CATEGORY}_SUCCESS`;
export const REMOVE_CATEGORY_FAILURE = `${REMOVE_CATEGORY}_FAILURE`;

export default {
    ADD_CATEGORY_REQUEST,
    ADD_CATEGORY_SUCCESS,
    ADD_CATEGORY_FAILURE,
    REMOVE_CATEGORY_REQUEST,
    REMOVE_CATEGORY_SUCCESS,
    REMOVE_CATEGORY_FAILURE
};
