export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const ADD_CATEGORY_REQUEST = `${ADD_CATEGORY}_REQUEST`;
export const ADD_CATEGORY_SUCCESS = `${ADD_CATEGORY}_SUCCESS`;
export const ADD_CATEGORY_FAILURE = `${ADD_CATEGORY}_FAILURE`;
export const REMOVE_CATEGORY_REQUEST = `${REMOVE_CATEGORY}_REQUEST`;
export const REMOVE_CATEGORY_SUCCESS = `${REMOVE_CATEGORY}_SUCCESS`;
export const REMOVE_CATEGORY_FAILURE = `${REMOVE_CATEGORY}_FAILURE`;
export const UPDATE_CATEGORY_REQUEST = `${UPDATE_CATEGORY}_REQUEST`;
export const UPDATE_CATEGORY_SUCCESS = `${UPDATE_CATEGORY}_SUCCESS`;
export const UPDATE_CATEGORY_FAILURE = `${UPDATE_CATEGORY}_FAILURE`;
export const START_UPDATING_CATEGORY = `START_UPDATING_CATEGORY`;
export const STOP_UPDATING_CATEGORY = `STOP_UPDATING_CATEGORY`;

export const ADD_PRODUCT_REQUEST = `${ADD_PRODUCT}_REQUEST`;
export const ADD_PRODUCT_SUCCESS = `${ADD_PRODUCT}_SUCCESS`;
export const ADD_PRODUCT_FAILURE = `${ADD_PRODUCT}_FAILURE`;
export const REMOVE_PRODUCT_REQUEST = `${REMOVE_PRODUCT}_REQUEST`;
export const REMOVE_PRODUCT_SUCCESS = `${REMOVE_PRODUCT}_SUCCESS`;
export const REMOVE_PRODUCT_FAILURE = `${REMOVE_PRODUCT}_FAILURE`;
export const UPDATE_PRODUCT_REQUEST = `${UPDATE_PRODUCT}_REQUEST`;
export const UPDATE_PRODUCT_SUCCESS = `${UPDATE_PRODUCT}_SUCCESS`;
export const UPDATE_PRODUCT_FAILURE = `${UPDATE_PRODUCT}_FAILURE`;
export const START_UPDATING_PRODUCT = `START_UPDATING_PRODUCT`;
export const STOP_UPDATING_PRODUCT = `STOP_UPDATING_PRODUCT`;

export default {
    ADD_CATEGORY_REQUEST,
    ADD_CATEGORY_SUCCESS,
    ADD_CATEGORY_FAILURE,
    REMOVE_CATEGORY_REQUEST,
    REMOVE_CATEGORY_SUCCESS,
    REMOVE_CATEGORY_FAILURE,
    UPDATE_CATEGORY_REQUEST,
    UPDATE_CATEGORY_SUCCESS,
    UPDATE_CATEGORY_FAILURE,
    START_UPDATING_CATEGORY,
    STOP_UPDATING_CATEGORY,
    ADD_PRODUCT_REQUEST,
    ADD_PRODUCT_SUCCESS,
    ADD_PRODUCT_FAILURE,
    REMOVE_PRODUCT_REQUEST,
    REMOVE_PRODUCT_SUCCESS,
    REMOVE_PRODUCT_FAILURE,
    UPDATE_PRODUCT_REQUEST,
    UPDATE_PRODUCT_SUCCESS,
    UPDATE_PRODUCT_FAILURE,
    START_UPDATING_PRODUCT,
    STOP_UPDATING_PRODUCT
};
