export const GET_PRODUCT = 'GET_PRODUCT';

export const GET_PRODUCT_REQUEST = `${GET_PRODUCT}_REQUEST`;
export const GET_PRODUCT_SUCCESS = `${GET_PRODUCT}_SUCCESS`;

export default {
    GET_PRODUCT_REQUEST,
    GET_PRODUCT_SUCCESS
};
