export const GET_APP_CONFIG = 'GET_APP_CONFIG';

export const GET_APP_CONFIG_REQUEST = `${GET_APP_CONFIG}_REQUEST`;
export const GET_APP_CONFIG_SUCCESS = `${GET_APP_CONFIG}_SUCCESS`;

export default {
    GET_APP_CONFIG_REQUEST,
    GET_APP_CONFIG_SUCCESS
};
