export const GET_DELIVERY_METHODS = 'GET_DELIVERY_METHODS';
export const GET_PAYMENT_METHODS = 'GET_PAYMENT_METHODS';

const GET_DELIVERY_METHODS_REQUEST = `${GET_DELIVERY_METHODS}_REQUEST`;
const GET_DELIVERY_METHODS_SUCCESS = `${GET_DELIVERY_METHODS}_SUCCESS`;
const GET_PAYMENT_METHODS_REQUEST = `${GET_PAYMENT_METHODS}_REQUEST`;
const GET_PAYMENT_METHODS_SUCCESS = `${GET_PAYMENT_METHODS}_SUCCESS`;
const RESET_OPTIONS = 'RESET_OPTIONS';

export default {
    GET_DELIVERY_METHODS_REQUEST,
    GET_DELIVERY_METHODS_SUCCESS,
    GET_PAYMENT_METHODS_REQUEST,
    GET_PAYMENT_METHODS_SUCCESS,
    RESET_OPTIONS
};
