const RESET_OPTIONS = 'RESET_OPTIONS';
const GET_DELIVERY_METHODS_REQUEST = 'GET_DELIVERY_METHODS_REQUEST';
const GET_DELIVERY_METHODS_SUCCESS = 'GET_DELIVERY_METHODS_SUCCESS';
const GET_PAYMENT_METHODS_REQUEST = 'GET_PAYMENT_METHODS_REQUEST';
const GET_PAYMENT_METHODS_SUCCESS = 'GET_PAYMENT_METHODS_SUCCESS';

export default {
    GET_DELIVERY_METHODS_REQUEST,
    GET_DELIVERY_METHODS_SUCCESS,
    GET_PAYMENT_METHODS_REQUEST,
    GET_PAYMENT_METHODS_SUCCESS,
    RESET_OPTIONS
};
